let assert = chai.assert;

describe('TestoviParser', function() {  
 describe('porediRezultate()', function() {

  it('Isti testovi u oba, isto rasporedjeni, bez gresaka', function() {
     let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":2,\"pending\":0,\"failures\":0,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Prvitest1\",\"fullTitle\":\"Prvitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Prvitest2\",\"fullTitle\":\"Prvitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[],\"passes\":[{\"title\":\"Prvitest1\",\"fullTitle\":\"Prvitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Prvitest2\",\"fullTitle\":\"Prvitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}",
      "{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":2,\"pending\":0,\"failures\":0,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Prvitest1\",\"fullTitle\":\"Prvitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Prvitest2\",\"fullTitle\":\"Prvitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[],\"passes\":[{\"title\":\"Prvitest1\",\"fullTitle\":\"Prvitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Prvitest2\",\"fullTitle\":\"Prvitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "100%");
     assert.equal(rezultat.greske.length, 0);
  });


  it('Isti testovi u oba, izmijesani, bez gresaka', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":3,\"pending\":0,\"failures\":0,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Drugitest1\",\"fullTitle\":\"Drugitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest2\",\"fullTitle\":\"Drugitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest3\",\"fullTitle\":\"Drugitestbezgresaka3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[],\"passes\":[{\"title\":\"Drugitest1\",\"fullTitle\":\"Drugitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest2\",\"fullTitle\":\"Drugitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest3\",\"fullTitle\":\"Drugitestbezgresaka3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}",
      "{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":3,\"pending\":0,\"failures\":0,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Drugitest3\",\"fullTitle\":\"Drugitestbezgresaka3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest1\",\"fullTitle\":\"Drugitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest2\",\"fullTitle\":\"Drugitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[],\"passes\":[{\"title\":\"Drugitest3\",\"fullTitle\":\"Drugitestbezgresaka3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest1\",\"fullTitle\":\"Drugitestbezgresaka1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Drugitest2\",\"fullTitle\":\"Drugitestbezgresaka2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "100%");
     assert.equal(rezultat.greske.length, 0);
   });


  it('Isti testovi u oba, isto rasporedjeni, u prvom svi padaju, u drugom prolaze', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":0,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Trecitestt1\",\"fullTitle\":\"Trecitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Trecitestt2\",\"fullTitle\":\"Trecitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Trecitestt1\",\"fullTitle\":\"Trecitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Trecitestt2\",\"fullTitle\":\"Trecitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}",
      "{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":2,\"pending\":0,\"failures\":0,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Trecitestt1\",\"fullTitle\":\"Trecitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Trecitestt2\",\"fullTitle\":\"Trecitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[],\"passes\":[{\"title\":\"Trecitestt1\",\"fullTitle\":\"Trecitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Trecitestt2\",\"fullTitle\":\"Trecitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "100%");
     assert.equal(rezultat.greske.length, 0);
   });


  it('Isti testovi u oba, izmijesani, jedan se popravi u drugom, preostala 2 padaju', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":0,\"pending\":0,\"failures\":3,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Cetvrtitestt1\",\"fullTitle\":\"Cetvrtitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt3\",\"fullTitle\":\"Cetvrtitest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt2\",\"fullTitle\":\"Cetvrtitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Cetvrtitestt1\",\"fullTitle\":\"Cetvrtitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt3\",\"fullTitle\":\"Cetvrtitest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt2\",\"fullTitle\":\"Cetvrtitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}",
      "{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":1,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Cetvrtitestt2\",\"fullTitle\":\"Cetvrtitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt3\",\"fullTitle\":\"Cetvrtitest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt1\",\"fullTitle\":\"Cetvrtitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Cetvrtitestt1\",\"fullTitle\":\"Cetvrtitest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Cetvrtitestt3\",\"fullTitle\":\"Cetvrtitest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Cetvrtitestt2\",\"fullTitle\":\"Cetvrtitest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "33.3%");
     assert.equal(rezultat.greske.length, 2);
   });



  it('Svi testovi razliciti, u prvom 1 pada u drugom 2', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":2,\"pending\":0,\"failures\":1,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Petitestt2\",\"fullTitle\":\"Prvipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Petitestt3\",\"fullTitle\":\"Prvipokusajtest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Petitestt1\",\"fullTitle\":\"Prvipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Petitestt1\",\"fullTitle\":\"Prvipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Petitestt2\",\"fullTitle\":\"Prvipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Petitestt3\",\"fullTitle\":\"Prvipokusajtest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}",
      "{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":0,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Petitestt2\",\"fullTitle\":\"Drugipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Petitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Petitestt2\",\"fullTitle\":\"Drugipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Petitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}");
     assert.equal(rezultat.promjena, "100%");
     assert.equal(rezultat.greske.length, 3);
   });


  it('Razliciti testovi, jedan zajednicki  - pada u prvom prolazi  drugom', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":3,\"tests\":3,\"passes\":2,\"pending\":0,\"failures\":1,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Sestitestt2\",\"fullTitle\":\"Drugipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt3\",\"fullTitle\":\"AABDrugipokusajtest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Sestitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Sestitestt2\",\"fullTitle\":\"Drugipokusajtest2\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt3\",\"fullTitle\":\"AABDrugipokusajtest3\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}",
      "{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":1,\"pending\":0,\"failures\":1,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"Drugipokus8ajtest8\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"Drugipokus8ajtest8\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Sestitestt1\",\"fullTitle\":\"AADrugipokusajtest1\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "66.7%");
     assert.equal(rezultat.greske.length, 1);
   });

  it('Provjera da li su greske sortirane leksikografski', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":4,\"tests\":4,\"passes\":2,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"AActest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AAbtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bztest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bzzytest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"AAbtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AActest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bztest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bzzytest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}",
      "{\"stats\":{\"suites\":4,\"tests\":4,\"passes\":2,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"AActest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AAbtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bztest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bzzytest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Sestitestt8\",\"fullTitle\":\"AAbtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"AActest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bztest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sestitestt1\",\"fullTitle\":\"Bzzytest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}]}");
     assert.equal(rezultat.promjena, "50%");
     assert.equal(rezultat.greske[0], "AAbtest");
     assert.equal(rezultat.greske[1], "AActest");
   });

   it('Provjera da li prvo uzima greske prvog pa drugog poredane leksikografski', function() {
    let rezultat = TestoviParser.porediRezultate("{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":0,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Sedmitest8\",\"fullTitle\":\"Cabtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sedmitestt1\",\"fullTitle\":\"Cchtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Sedmitest8\",\"fullTitle\":\"Cabtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Sedmitestt1\",\"fullTitle\":\"Cchtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}",
    "{\"stats\":{\"suites\":2,\"tests\":2,\"passes\":0,\"pending\":0,\"failures\":2,\"start\":\"2021-11-05T15:00:26.343Z\",\"end\":\"2021-11-05T15:00:26.352Z\",\"duration\":9},\"tests\":[{\"title\":\"Kucatest8\",\"fullTitle\":\"aabtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Kucatestt1\",\"fullTitle\":\"aaatest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"pending\":[],\"failures\":[{\"title\":\"Kucatest8\",\"fullTitle\":\"aabtest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}},{\"title\":\"Kucatestt1\",\"fullTitle\":\"aaatest\",\"file\":null,\"duration\":1,\"currentRetry\":0,\"speed\":\"fast\",\"err\":{}}],\"passes\":[]}");
     assert.equal(rezultat.promjena, "100%");
     assert.equal(rezultat.greske[0], "Cabtest");
     assert.equal(rezultat.greske[1], "Cchtest");
     assert.equal(rezultat.greske[2], "aaatest");
     assert.equal(rezultat.greske[3], "aabtest");
   });






  
  

 
  
   
  });
});
